---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-k8-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8-test
      version: blue
  template:
    metadata:
      name: k8-test-demo
      labels:
        app: k8-test
        version: blue
    spec:
      containers:
      - name: k8-demo
        image: anees2022/titanic:anis
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service 
metadata:
  name: k8-demo
  labels:
    app: k8-test
spec:
  selector:
    app: k8-test
    version: blue
  type: NodePort
  ports:
  - nodePort: 30006
    port: 80
    targetPort: 5000
